DATASETS_FOLDER_ID = 'datasets'
DATASETS_SPECIES_FOLDER_ID = 'species'
DATASETS_ENVIRONMENTAL_FOLDER_ID = 'environmental'
DATASETS_CLIMATE_FOLDER_ID = 'climate'

FUNCTIONS_FOLDER_ID = 'functions'

KNOWLEDGEBASE_FOLDER_ID = 'knowledgebase'
