DATASETS_FOLDER_ID = 'datasets'
DATASETS_FOLDER_TITLE = 'Reference Data Sets'

DATASETS_SPECIES_FOLDER_ID = 'species'
DATASETS_SPECIES_FOLDER_TITLE = 'Biological Data'

DATASETS_ENVIRONMENTAL_FOLDER_ID = 'environmental'
DATASETS_ENVIRONMENTAL_FOLDER_TITLE = 'Environmental Data'

DATASETS_CLIMATE_FOLDER_ID = 'climate'
DATASETS_CLIMATE_FOLDER_ID = 'Climate Data'

TOOLKITS_FOLDER_ID = 'toolkit'
TOOLKITS_FOLDER_TITLE = 'Toolkits'

KNOWLEDGEBASE_FOLDER_ID = 'knowledgebase'
KNOWLEDGEBASE_FOLDER_TITLE = 'Knowledge Base'

EXPERIMENTS_FOLDER_ID = 'experiments'
EXPERIMENTS_FOLDER_TITLE = 'Experiments'

FUNCTIONS_FOLDER_ID = TOOLKITS_FOLDER_ID # TODO: deprecate
